### ISSUE TITLE
No mock config for F25

### ISSUE THREAD

**Issue by paulcarroty** [nrechn/mock-travis#4]
Hello, I tried to rebuild your example for F25:
```
Start setting up mock environment

ERROR: Could not find required config file: /etc/mock/fedora-25-x86_64.cfg

ERROR:   If you're trying to specify a path, include the .cfg extension, e.g. -r ./target.cfg
```
Full log is [here](https://travis-ci.org/paulcarroty/travis-rpm-test/builds/169738687).

**Comment by nrechn** [comment]
Sorry for my late reply. 

I just updated relate Docker image. The `mock` should now support `fedora-25-x86_64.cfg`.
