### ISSUE TITLE
packages_extra_repo doesn't work

### ISSUE THREAD

**Issue by paulcarroty** [nrechn/mock-travis#7]
`$SUBJ`. Any packages/repos doesn't used in build process.

**Comment by nrechn** [comment]
Hi @paulcarroty ,

Sorry for late response. I was busy on my uni final exams of this semester.

My misspell fault which caused packages/repos did not work.

It should be fixed now. Please check again.

Hope it works now.

**Comment by paulcarroty** [comment]
Seems like it works, thanks!
